import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Provider from '@/lib/Provider';

import "./globals.css";

const inter = Space_Grotesk({
    weight: ['400', '500', '600', '700'],
    subsets: ['latin', 'latin-ext']
});

export const metadata: Metadata = {
  title: "Availabowl Admin App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <Provider>
            <body className={inter.className}>{children}</body>
        </Provider>
    </html>
  );
}
